"""Generate the Markdown sources consumed by the VitePress website."""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path

from nbconvert import MarkdownExporter


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
NOTEBOOKS = DOCS / "notebooks"
TUTORIALS = DOCS / "tutorials"
API_REFERENCE = DOCS / "api.md"

API_FRONTMATTER = "---\noutline: deep\n---\n\n"
PUBLIC_API_SYMBOLS = (
    "Catalogue",
    "Instrument",
    "Instruments",
    "plot_bands",
    "plot_srf",
)
GENERATED_NOTICE = (
    "<!-- Generated by docs/vitepress.py. Do not edit directly. -->\n\n"
)


def _executable(name: str) -> str:
    """Return an executable from the active Python environment or PATH."""

    environment_executable = Path(sys.executable).parent / name
    if environment_executable.is_file():
        return str(environment_executable)

    executable = shutil.which(name)
    if executable is None:
        raise RuntimeError(
            f"{name!r} is required to generate the documentation"
        )
    return executable


def _public_api_only(markdown: str) -> str:
    """Keep the package overview and symbols exposed directly by ``xeo``."""

    markdown = re.sub(
        r"\n\*\*Modules:\*\*\n\n(?:- .*\n)+",
        "\n",
        markdown,
        count=1,
    )

    section_pattern = re.compile(r"^### `([^`]+)`\s*$", re.MULTILINE)
    section_matches = list(section_pattern.finditer(markdown))
    if not section_matches:
        raise RuntimeError("griffe2md generated no API sections")

    expected_sections = {f"xeo.{symbol}" for symbol in PUBLIC_API_SYMBOLS}
    retained_sections: list[str] = []
    found_sections: set[str] = set()

    for index, match in enumerate(section_matches):
        section_name = match.group(1)
        if section_name not in expected_sections:
            continue

        section_end = (
            section_matches[index + 1].start()
            if index + 1 < len(section_matches)
            else len(markdown)
        )
        retained_sections.append(markdown[match.start() : section_end].rstrip())
        found_sections.add(section_name)

    missing_sections = expected_sections.difference(found_sections)
    if missing_sections:
        missing = ", ".join(sorted(missing_sections))
        raise RuntimeError(f"griffe2md omitted public API sections: {missing}")

    package_overview = markdown[: section_matches[0].start()].rstrip()
    public_markdown = "\n\n".join([package_overview, *retained_sections]) + "\n"

    # Griffe resolves these classes to their implementation module. Point
    # links back to the public sections retained above.
    public_markdown = re.sub(
        r"#xeo\.(?:axioms|xeo)\.(Catalogue|Instrument|Instruments)",
        r"#xeo.\1",
        public_markdown,
    )

    # VitePress otherwise slugifies ``xeo.Catalogue`` as ``xeo-catalogue``,
    # which does not match the fully qualified links emitted by griffe2md.
    public_symbols = "|".join(re.escape(symbol) for symbol in PUBLIC_API_SYMBOLS)
    public_markdown = re.sub(
        rf"^### `(xeo\.(?:{public_symbols}))`\s*$",
        r"### `\1` {#\1}",
        public_markdown,
        flags=re.MULTILINE,
    )

    # Keep class names qualified, but use compact member labels in the page
    # outline. Custom anchors preserve griffe2md's fully qualified links and
    # avoid collisions between repeated names such as ``to_dict``.
    public_markdown = re.sub(
        r"^#### `xeo\.(Catalogue|Instrument|Instruments)\.([^`]+)`\s*$",
        lambda match: (
            f"#### `{match.group(2)}` "
            f"{{#xeo.{match.group(1)}.{match.group(2)}}}"
        ),
        public_markdown,
        flags=re.MULTILINE,
    )
    return public_markdown


def generate_api_reference() -> None:
    """Generate a public-only API reference with VitePress frontmatter."""

    subprocess.run(
        [
            _executable("griffe2md"),
            "xeo",
            "-o",
            str(API_REFERENCE.relative_to(ROOT)),
        ],
        cwd=ROOT,
        check=True,
    )

    generated = API_REFERENCE.read_text(encoding="utf-8").lstrip()
    generated = _public_api_only(generated)
    API_REFERENCE.write_text(
        API_FRONTMATTER + generated,
        encoding="utf-8",
    )


def _tutorial_title(markdown: str, fallback: str) -> str:
    """Read the first level-one heading from converted notebook Markdown."""

    heading = re.search(r"^#\s+(.+?)\s*$", markdown, flags=re.MULTILINE)
    return heading.group(1) if heading else fallback.replace("_", " ").title()


def _normalize_markdown(markdown: str) -> str:
    """Remove generated trailing whitespace and normalize the final newline."""

    lines = (line.rstrip() for line in markdown.splitlines())
    return "\n".join(lines).strip() + "\n"


def _write_notebook_assets(outputs: dict[str, bytes]) -> None:
    """Write assets emitted by nbconvert inside the tutorials directory."""

    tutorials_root = TUTORIALS.resolve()
    for relative_name, contents in outputs.items():
        destination = (TUTORIALS / relative_name).resolve()
        if tutorials_root not in destination.parents:
            raise ValueError(f"invalid notebook asset path: {relative_name}")
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(contents)


def generate_tutorials() -> None:
    """Convert tutorial notebooks to Markdown and generate their index."""

    notebooks = sorted(NOTEBOOKS.glob("*.ipynb"))
    if not notebooks:
        raise RuntimeError(f"no tutorial notebooks found in {NOTEBOOKS}")

    TUTORIALS.mkdir(parents=True, exist_ok=True)
    notebook_stems = {notebook.stem for notebook in notebooks}

    # Remove only stale files previously created by this generator.
    for markdown_path in TUTORIALS.glob("*.md"):
        if markdown_path.name == "index.md":
            continue
        text = markdown_path.read_text(encoding="utf-8")
        if (
            text.startswith(GENERATED_NOTICE)
            and markdown_path.stem not in notebook_stems
        ):
            markdown_path.unlink()
            shutil.rmtree(
                TUTORIALS / f"{markdown_path.stem}_files",
                ignore_errors=True,
            )

    exporter = MarkdownExporter()
    tutorial_links: list[tuple[str, str]] = []

    for notebook in notebooks:
        asset_directory = TUTORIALS / f"{notebook.stem}_files"
        shutil.rmtree(asset_directory, ignore_errors=True)

        markdown, resources = exporter.from_filename(
            str(notebook),
            resources={
                "unique_key": notebook.stem,
                "output_files_dir": asset_directory.name,
            },
        )
        markdown = _normalize_markdown(markdown)

        destination = TUTORIALS / f"{notebook.stem}.md"
        destination.write_text(
            GENERATED_NOTICE + markdown,
            encoding="utf-8",
        )
        _write_notebook_assets(resources.get("outputs", {}))

        tutorial_links.append(
            (_tutorial_title(markdown, notebook.stem), notebook.stem)
        )

    index_lines = [
        GENERATED_NOTICE.rstrip(),
        "",
        "# Tutorials",
        "",
        "Learn the `xeo` API through these step-by-step tutorials.",
        "",
    ]
    index_lines.extend(
        f"- [{title}](./{stem})" for title, stem in tutorial_links
    )
    TUTORIALS.joinpath("index.md").write_text(
        "\n".join(index_lines) + "\n",
        encoding="utf-8",
    )


def copy_contributing_guide() -> None:
    """Copy the root contributing guide into the documentation site."""

    source = ROOT / "CONTRIBUTING.md"
    destination = DOCS / "contributing.md"
    destination.write_bytes(source.read_bytes())


def main() -> None:
    """Generate every derived VitePress Markdown document."""

    generate_api_reference()
    generate_tutorials()
    copy_contributing_guide()

    print(f"Generated API reference: {API_REFERENCE.relative_to(ROOT)}")
    print(f"Generated tutorials: {TUTORIALS.relative_to(ROOT)}")
    print("Copied contributing guide: docs/contributing.md")


if __name__ == "__main__":
    main()
